# Generated by Django 5.0 on 2025-03-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text="Separate each feature with a '|'. Example: 'Feature 1|Feature 2|Feature 3'", null=True),
        ),
    ]
