# Generated by Django 5.0 on 2025-03-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_description_project_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
    ]
